### ISSUE TITLE
Pairing is not working

### ISSUE THREAD

**Issue by Moose7378** [bitfocus/companion-module-android-tv#17]
With the settings correct as instructed, pairing seems to not be working. I reset the TV and even factory reset it. I had no luck. Using 2020 TCL Beyond TV5. Companion recognizes the units in the Target IP, but I can't get anything else to work.

**Comment by zerbzman** [comment]
Hey, sorry! I am very close to releasing a new version that should fix this. Can you shoot me an email at my GitHub username at gmail.com and I'll send you a dropbox link to the module to test?

**Comment by MarekPro1** [comment]
Hello for me its also not working on panasonic android tv can I get also the module to test it? Thank you.

**Comment by zerbzman** [comment]
Hey @MarekPro1, if you shoot me an email at my GitHub username at gmail.com, I'll send you a dropbox link.

**Comment by MarekPro1** [comment]
Soo I got it firt question is that the file has 21 000 files that needs to be extracted is that right? My computer it is gona take 20min. 
![image](https://github.com/user-attachments/assets/ed8b08f6-79fe-4fa1-a2d3-293f1f71cb71)

**Comment by zerbzman** [comment]
Yeah, the developer version uses the pre-built files. Hopefully should have the new version out soon.

**Comment by MarekPro1** [comment]
Hello @zerbzman i tried the version you sent me it doesn't work, but I don't know for sure that i have the newer version because in info it says the older version 2.0.2 should it be like this?
![image](https://github.com/user-attachments/assets/aa7b17e5-ec8d-4c80-924f-5084d9ff0082)

**Comment by zerbzman** [comment]
No, it should say 0.0.0 because it's a dev module. What could be happening is the companion-module folder needs to get moved up one folder. I had this issue initially when testing on windows. When unzipping, it added a parent folder in the folder where companion looks. So `Special companion dev folder->companion-module-androidtv 5->companion-module-androidtv` needs to be moved up one to be `Special companion dev folder->companion-module-androidtv`.

**Comment by MarekPro1** [comment]
Did it like that tried it again still it sais 2.0.2 but one difference is that i have _companion-module-androidtv **4**_

**Comment by zerbzman** [comment]
gotcha, either will work. You may just want to go over the instructions again and double check things.

**Comment by MarekPro1** [comment]
Hello I tried it again a it still says version 2.0.2.

**Comment by MarekPro1** [comment]
Hello I again want to help, to make this work! Can you give me some instructions to test it?

**Comment by zerbzman** [comment]
@MarekPro1 just sent you another version that might help.

**Comment by rluin** [comment]
Hello, i am trying to connect a chromcast with google tv. My steps are as following 
add module 
insert ip
save
add putton pair and pincode
press button pair 
Then nothing happens 

When i use the google tv app the code pops up and can register

Any ideas?

**Comment by zerbzman** [comment]
Hey @rluin,

Can you shoot me an email at my GitHub username at gmail.com and I'll send you a dropbox link to the module to test?
