### ISSUE TITLE
Packaging Issue

### ISSUE THREAD

**Issue by zerbzman** [bitfocus/companion-module-android-tv#2]
There is an issue after packaging that inhibits this module from connecting to a device. It errors out looking for a required file outside of the packaged file.

**Comment by MeestorX** [comment]
https://bitfocusio.slack.com/archives/C03SXQBFDB2/p1675611691996619?thread_ts=1675550665.830109&cid=C03SXQBFDB2

Maybe?

**Comment by zerbzman** [comment]
Yes, the issue that I'm having is that the file it's looking for is in node_modules and copies it with the folder structure and not just the file.

`{companion-module}/node_modules/androidtv-remote/dist/pairing/pairingmessage.proto` copies to `pkg/node_modules/androidtv-remote/dist/pairing/pairingmessage.proto` instead of copying to `pkg/pairingmessage.proto` where the file is looking for it.
