### ISSUE TITLE
Module loads wrong MAC address

### ISSUE THREAD

**Issue by elliotmatson** [bitfocus/companion-module-android-tv#22]
We have a HiSense TV, and pairing seems to work ok, but the MAC address has the first character removed and a space at the end. The MAC address starts with a 0, so maybe the module isn't including leading 0's when converting to text?

**Comment by elliotmatson** [comment]
Looking further, maybe this is a bug in macfromip?

**Comment by zerbzman** [comment]
Hey @elliotmatson,

Yeah, there are issues with the current one. Can you shoot me an email at my GitHub username at gmail.com and I'll send you a dropbox link to the module to test?
